name: anyen_clinic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  fab_circular_menu_plus: ^0.0.3
  permission_handler: ^12.0.0
  image_picker: ^1.0.2
  camera: ^0.11.1
  record: ^5.0.0
  audioplayers: ^5.2.1
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_gauges: ^29.1.39
  flutter_webrtc: 0.12.10
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.1.0
  url_launcher: ^6.1.5
  app_links: ^3.5.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  path: ^1.8.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^19.1.0
  socket_io_client: ^2.0.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" 

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 700
    - family: Inter_bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Inter_medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 900
    - family: Inter_medium
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 800

  assets:
    - assets/images/
    - assets/fonts/
    - assets/config/.env
