GET http://localhost:5000/api/user/ssssss

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "phone_number":"+8423456855",
    "password":"tttRSJSJSJ%%2222"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "phone_number":"+84397813398",
    "password":"TTSHS7sssh**"
}

###
POST http://localhost:5000/api/otp/send-otp
Content-Type: application/json

{
    "phone_number":""
}

###
POST http://localhost:5000/api/otp/verify-otp
Content-Type: application/json

{
    "phone_number":"+84397813398",
    "otp": "123452"
}
###
POST http://localhost:5000/api/auth/reset-pass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdmM2U0NmIzLTg3NGYtNDcxNC1iZDIyLTQ4MDRjMDQ2OGRkNSIsInBob25lX251bWJlciI6Iis4NDM5NzgxMzM5OCIsInJvbGVzIjpbInBhdGllbnQiXSwiaWF0IjoxNzQ0MTEyNDQ5LCJleHAiOjE3NDQxMTI3NDl9.xtoBL1_Ciai0x9x1n1ItIHmHoQUZ9wGazV_--deoy0M
Content-Type: application/json
{
    "oldPassword":"TTSHS7sssh**",
    "newPassword": "TTSHS7sssh**123"
}

###
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdmM2U0NmIzLTg3NGYtNDcxNC1iZDIyLTQ4MDRjMDQ2OGRkNSIsInBob25lX251bWJlciI6Iis4NDM5NzgxMzM5OCIsInJvbGVzIjpbInBhdGllbnQiXSwiaWF0IjoxNzQ0MTAzOTU2LCJleHAiOjE3NDQxMDQyNTZ9.1Ji7xyJfJ0TwU87I61LfhtK-uFg3EDqfbnE0KSErWcI

###
POST http://localhost:5000/api/auth/refresh-token/
refresh_token: 



