GET http://localhost:5000/api/user/ssssss

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "phone_number":"+8423456855",
    "password":"RSJSJSJ%%2222"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "phone_number":"+8",
    "password":""
}

###
POST http://localhost:5000/api/otp/send-otp
Content-Type: application/json

{
    "phone_number":""
}

###
POST http://localhost:5000/api/otp/verify-otp
Content-Type: application/json

{
    "phone_number":"",
    "otp": ""
}

###
GET http://localhost:5000/api/user/
Authorization: 

###
POST http://localhost:5000/api/auth/refresh-token/
refresh_token: 



